version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./pipeline.log:/app/pipeline.log
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:
  
networks:
  app_network:
    driver: bridge
